GET http://127.0.0.1:8000/api/pets


###
POST http://127.0.0.1:8000/api/pets
Accept: application/json
Content-Type: application/json

{
    "name": "Black white",
    "especie": "Mamba",
    "color": "black",
    "tamanho": "Pequeno"
}


###
GET http://127.0.0.1:8000/api/pets/1

###
PUT http://127.0.0.1:8000/api/pets/1
Accept: application/json
Content-Type: application/json

{
    "name": "Neve",
    "especie": "Coelho",
    "color": "white",
    "tamanho": "Pequeno"
}

###
DELETE http://127.0.0.1:8000/api/pets/2
Accept: application/json
